project:
  type: website
  preview:
    port: 4100

website:
  title: "OpenPipelines"
  description: "Best-practice workflows for single-cell single- and multi-omics data"
  image: "images/logo.svg"
  site-url: https://openpipelines.bio
  repo-url: https://github.com/openpipelines-bio/website
  repo-actions: [edit, issue] 
  google-analytics: G-KKE3LFPPV8

  page-footer:
    left: "&copy; OpenPipelines.bio 2022"

  navbar:
    logo: "images/logo.svg"
    title: false
    left:
      - href: index.qmd
        text: Home
      - fundamentals/index.qmd
      - user_guide/index.qmd
      - contributing/index.qmd
      - href: components/index.qmd
        text: Reference
      - team/index.qmd

    right:
      - icon: github
        url: https://github.com/openpipelines-bio/openpipeline
        aria-label: GitHub
  sidebar:
    - id: reference
      title: Reference
      contents: components
      collapse-level: 3
    - id: guide
      title: Guide
      contents:
        - id: fundamentals
          collapse-level: 3
          section: Fundamentals
          contents: fundamentals/*
        - id: user_guide
          section: User guide
          collapse-level: 3
          contents: user_guide/*
        - id: contributing
          collapse-level: 3
          section: Contributing
          contents: contributing/*
        - id: more_information
          collapse-level: 3
          section: More information
          contents: more_information/*

format:
  html:
    theme: [simplex, theme.scss]
    css: styles.css
    toc: true


filters:
  - d2

