project:
  type: website
  preview:
    port: 4100

website:
  title: "OpenPipelines"
  description: "Best-practice workflows for single-cell single- and multi-omics data"
  image: "images/logo.svg"
  site-url: https://openpipelines.bio
  repo-url: https://github.com/openpipelines-bio/website
  repo-actions: [edit, issue] 
  google-analytics: G-KKE3LFPPV8

  page-footer:
    left: "&copy; OpenPipelines.bio 2022"

  navbar:
    logo: "images/logo.svg"
    title: false
    left:
      - href: index.qmd
        text: Home
      - guide/index.qmd
      - contributing/index.qmd
      - href: components/index.qmd
        text: Reference
      - team/index.qmd

    right:
      - icon: github
        url: https://github.com/openpipelines-bio/openpipeline
        aria-label: GitHub
  sidebar:
    - id: components
      collapse-level: 4
      title: Components
      contents: components
    - id: guide
      collapse-level: 3
      title: Guide
      contents: guide
    - id: contributing
      collapse-level: 3
      title: Contributing
      contents:  contributing

format:
  html:
    theme: [simplex, theme.scss]
    css: styles.css
    toc: true



