on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render project

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2"
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - uses: viash-io/viash-actions/setup@v3
      
      - name: Install Viash
        uses: viash-io/viash-actions/setup@main
          
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - run: |
          REPO_PATH=`git rev-parse --show-toplevel`
          PROJ_DIR="$REPO_PATH/_openpipeline"

          echo "REPO_PATH: $REPO_PATH"
          echo "PROJ_DIR: $PROJ_DIR"

          # if submodule is not available, initialise it
          if [ ! -d "$PROJ_DIR" ]; then
            $(cd "$REPO_PATH" && git submodule update --init --recursive)
          fi

          # undo changes and sync test resources
          $(cd "$PROJ_DIR" && git clean -fxd -e resources_test && viash run src/download/sync_test_resources/config.vsh.yaml)

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          force: false
          clean-exclude: pr-preview/

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto